# Generated by Django 5.1.1 on 2024-09-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars')),
                ('reviews_stars', models.FloatField()),
                ('reviews_small', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Avatars',
                'verbose_name_plural': 'Avatars',
            },
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Book Section',
                'verbose_name_plural': 'Book Sections',
            },
        ),
    ]
