# Generated by Django 5.1.1 on 2024-09-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reviews_remove_avatars_reviews_small_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews_smoll',
            new_name='reviews_small',
        ),
    ]
