# Generated by Django 5.1.1 on 2024-09-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_reviews_smoll_reviews_reviews_small'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatars',
        ),
        migrations.DeleteModel(
            name='BookSection',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='HeaderText',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
