# Generated by Django 5.1.1 on 2024-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star_rating',
            field=models.IntegerField(),
        ),
    ]
