# Generated by Django 5.1.1 on 2024-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reviews_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='total_reviews',
            field=models.FloatField(),
        ),
    ]
