# Generated by Django 5.1.1 on 2024-09-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reviews_star_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatars',
            old_name='avatar1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='avatars',
            name='avatar2',
        ),
        migrations.RemoveField(
            model_name='avatars',
            name='avatar3',
        ),
        migrations.RemoveField(
            model_name='avatars',
            name='avatar4',
        ),
    ]
