# Generated by Django 5.1.1 on 2024-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_avatar1_avatars_image_remove_avatars_avatar2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='image',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
