# Generated by Django 5.1.1 on 2024-09-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_avatars_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='star_rating',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='total_reviews',
            new_name='total',
        ),
    ]
