# Generated by Django 5.1.1 on 2024-09-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_star_rating_reviews_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='avatars')),
                ('stars', models.FloatField()),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'AllReviews',
                'verbose_name_plural': 'AllReviews',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ContentBlock',
                'verbose_name_plural': 'ContentBlock',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='bloks')),
                ('note', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Delegate',
                'verbose_name_plural': 'Delegate',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('quastion', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('blockquote', models.TextField(max_length=255)),
                ('note', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Habits',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='Inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Inside',
                'verbose_name_plural': 'Inside',
            },
        ),
        migrations.CreateModel(
            name='Introducing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('quastion', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('blockquote', models.TextField(max_length=255)),
                ('note', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Introducing',
                'verbose_name_plural': 'Introducing',
            },
        ),
        migrations.CreateModel(
            name='MeetAuther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auther')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'MeetAuther',
                'verbose_name_plural': 'MeetAuther',
            },
        ),
        migrations.CreateModel(
            name='Modern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tablet')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modern',
                'verbose_name_plural': 'Modern',
            },
        ),
        migrations.CreateModel(
            name='Modernebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modernebook',
                'verbose_name_plural': 'Modernebook',
            },
        ),
        migrations.CreateModel(
            name='Winback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='bloks')),
                ('note', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Winback',
                'verbose_name_plural': 'Winback',
            },
        ),
        migrations.CreateModel(
            name='Workless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='tablet')),
            ],
            options={
                'verbose_name': 'Workless',
                'verbose_name_plural': 'Workless',
            },
        ),
    ]
