# Generated by Django 5.1.1 on 2024-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_allreviews_contentblock_delegate_habits_inside_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Block'},
        ),
        migrations.RenameField(
            model_name='delegate',
            old_name='description',
            new_name='description1',
        ),
        migrations.RemoveField(
            model_name='habits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meetauther',
            name='description',
        ),
        migrations.RemoveField(
            model_name='winback',
            name='description',
        ),
        migrations.RemoveField(
            model_name='winback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workless',
            name='description',
        ),
        migrations.AddField(
            model_name='delegate',
            name='description2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='description3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habits',
            name='description1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habits',
            name='description2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetauther',
            name='description1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetauther',
            name='description2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winback',
            name='description1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winback',
            name='description2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winback',
            name='description3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winback',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='winbloks'),
        ),
        migrations.AddField(
            model_name='winback',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='winbloks'),
        ),
        migrations.AddField(
            model_name='workless',
            name='description1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workless',
            name='description2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
