# Generated by Django 5.1.1 on 2024-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsMambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='avatars')),
                ('stars', models.FloatField()),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'ReviewsMemrers',
                'verbose_name_plural': 'ReviewsMembers',
            },
        ),
        migrations.RemoveField(
            model_name='allreviews',
            name='description',
        ),
        migrations.RemoveField(
            model_name='allreviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='allreviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='allreviews',
            name='position',
        ),
        migrations.RemoveField(
            model_name='allreviews',
            name='stars',
        ),
    ]
