# Generated by Django 5.1.1 on 2024-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reviewsmambers_remove_allreviews_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmambers',
            name='image',
            field=models.ImageField(upload_to='reviews_mambers'),
        ),
    ]
