# Generated by Django 5.1.1 on 2024-09-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_reviewsmambers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phon_image')),
            ],
        ),
        migrations.AlterField(
            model_name='winback',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='winback'),
        ),
        migrations.AlterField(
            model_name='winback',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='winback'),
        ),
    ]
