# Generated by Django 5.1.1 on 2024-09-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_phonimage_alter_winback_image1_alter_winback_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headertext',
            name='image',
        ),
    ]
