# Generated by Django 5.1.1 on 2024-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_footertext_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='text',
        ),
        migrations.AddField(
            model_name='footertext',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footertext',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
