# Generated by Django 5.1.1 on 2024-09-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_footertext_text_footertext_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertext',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='text2',
        ),
    ]
