# Generated by Django 5.1.1 on 2024-09-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_text1_footertext_text_remove_footertext_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertext',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='footertext',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
