# Generated by Django 5.1.1 on 2024-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_text_footertext_text1_footertext_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ContactsName',
                'verbose_name_plural': 'ContactsName',
            },
        ),
    ]
