# Generated by Django 5.1.1 on 2024-09-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contactsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsname',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactsname',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
