# Generated by Django 5.1.1 on 2024-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_contactsname_tag_alter_contactsname_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=255)),
                ('html_url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Six Blocks',
                'verbose_name_plural': 'Six Blocks',
            },
        ),
    ]
