# Generated by Django 5.1.1 on 2024-09-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_sixblocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SixBlocks',
            new_name='Charters',
        ),
        migrations.AlterModelOptions(
            name='charters',
            options={'verbose_name': 'Charters', 'verbose_name_plural': 'Charters'},
        ),
    ]
