# Generated by Django 5.1.1 on 2024-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_sixblocks_charters_alter_charters_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charters',
            name='html_url',
            field=models.CharField(max_length=255),
        ),
    ]
